# docker-compose.yml

version: '3.8'

services:
  web:
    container_name: web
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && rails db:create db:migrate && rails server -b 0.0.0.0"
    volumes:
      - .:/keeper-notes
    ports:
      - "3000:3000"
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
    networks:
      - backend

  redis:
    image: "redis:alpine"
    container_name: redis
    command: redis-server
    ports:
      - "6379:6379"
    networks:
      - backend
networks:
  backend:
    driver: bridge
