#
# Class for Devise generated User
#   field name - required
#   field email - required
#
# acts_as_token_authenticatable for api requests
#   generated by simple_token_authentication gem
#
class User < ApplicationRecord
  rolify
  acts_as_token_authenticatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :notes

  validates :name, presence: true
end
