#
# Class for Devise generated User
#   field name - required
#   field email - required
#
# acts_as_token_authenticatable for api requests
#   generated by simple_token_authentication gem
#
class User < ApplicationRecord
  rolify
  acts_as_token_authenticatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :notes

  validates :name, presence: true

  after_create :create_export_folder

  private

  #
  # This folder will store the exports for the user
  # The exports will be create by: ExportNotesWorker
  # And will be deleted after 24 hours by: ExportFileDeletionWorker
  #
  def create_export_folder
    Dir.mkdir("#{Rails.root}/public/#{id.to_s}") unless Dir.exists?("#{Rails.root}/public/#{id.to_s}")
  end
end
